# madlibs
import pyfiglet
ascii_banner = pyfiglet.figlet_format("Lucifer's first git tool")
print(ascii_banner)
print("Hey there :), A mad lib is waiting for you!\nRead it thoroughly :)\n")
print("According to a report in yesterday’s newspaper \n1._____ police dog was taken to Raj Bhavan \n2.______ Monday. This was to trace the \n3._______ of the very important horse which \n4._______ reported missing on Sunday. The dog picked \n5._______ the scent on some traces of \n6._______ and ran a few yards before losing the \n7._______. The police have launched a vigorous \n8.________ into the whole affair. They have \n9._______ the services of a forensic expert, \n10._______ fingerprint expert and a photographer. \n11.________ are now fourteen horses at Raj Bhavan \n12.__________ are kept in a large shed near the gate")
print("\n* Just type 1 and enter to start the test :)")
print("* Options will be given once you start the test.\n* And please go by order from 1-12 question order :)")
choice = int(input("* Enter your choice : "))
print("\n")
if choice == 1:
    print("Welcome to the test!")
    print("Now comes the mad lib with empty blanks.\nYou will be given 12 words to fill in the blanks!\nAll the best guys!\n")
    print("Options are:\nQuestion 1 :\na) once.\nb) a.\nc) new.\n\nQuestion 2 :\na) at.\nb) next.\nc) on.\n\nQuestion 3 :\na) killers.\nb) dogs.\nc) police.\n\nQuestion 4 :\na) has.\nb) were.\nc) was.\n\nQuestion 5 :\na) on.\nb) at.\nc) up.\n\nQuestion 6 :\na) those.\nb) blood.\nc) report.\n\nQuestion 7 :\na) bet.\nb) track.\nc) game.\n\nQuestion 8 :\na) search.\nb) investigation.\nc) campaign.\n\nQuestion 9 :\na) given up.\nb) requestioned.\nc) report.\n\nQuestion 10 :\na) a.\nb) an.\nc) two.\n\nQuestion 11 :\na) there.\nb) we.\nc) say.\n\nQuestion 12 :\na) who.\nb) where.\nc) which.\n")
    print("Go by order plz :)")
    print("Its answers time!!\n")
    first = input("Enter 1 = ")
    second = input("Enter 2 = ")
    third = input("Enter 3 = ")
    fourth = input("Enter 4 = ")
    fifth = input("Enter 5 = ")
    sixth = input("Enter 6 = ")
    seventh = input("Enter 7 = ")
    eight = input("Enter 8 = ")
    ninth = input("Enter 9 = ")
    tenth = input("Enter 10 = ")
    eleventh = input("Enter 11 = ")
    twelveth = input("Enter 12 = ")
    print("\n")
    print("Good work!, now lets see your passage with your answers filled in it :)\n")
    print("According to a report in yesterday’s newspaper " + first + " \npolice dog was taken to Raj Bhavan " + second +" \nMonday. This was to trace the " + third + " \nof the very important horse which " + fourth + " \nreported missing on Sunday. The dog picked " + fifth + " \nthe scent on some traces of " + sixth + " \nand ran a few yards before losing the " + seventh + " \nThe police have launched a vigorous " + eight + " \ninto the whole affair. They have " + ninth + " \nthe services of a forensic expert, " + tenth + " \nfingerprint expert and a photographer " + eleventh + " \nare now fourteen horses at Raj Bhavan " + twelveth + " \nare kept in a large shed near the gate ")
    print("\n")
    print("There you go!\nThank you for participating in this game :)")
else:
    print("Thanks for participating!\nCome again next time :)")